sudo: required
services:
  - docker

before_install:
  - docker build -t power8ce/learning-docker-react -f Dockerfile.dev .

script:
  - docker run power8ce/learning-docker-react npm run test -- --coverage